import type { AreaBrief, AreaPark } from './area-pack';

/**
 * Printable field sheet for a map area (#10): a clean, self-contained HTML doc (no JS/Chakra) listing the
 * parks in the viewport + their key field facts and nearby POI counts, designed to print or save offline.
 * Mirrors `lib/trip-brief-html.ts` (same palette/print CSS) so the two artifacts look like one family.
 */
function esc(s: string | null | undefined): string {
  return String(s ?? '').replace(/[&<>"']/g, (ch) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch] as string
  ));
}
function coords(lat: number | null | undefined, lng: number | null | undefined): string {
  return lat != null && lng != null ? `${lat.toFixed(5)}, ${lng.toFixed(5)}` : '—';
}

const LAYER_LABEL: Record<string, string> = {
  campgrounds: 'campgrounds',
  visitorcenters: 'visitor centers',
  thingstodo: 'things to do',
  alerts: 'active alerts',
};

export function areaFieldHtml(brief: AreaBrief): string {
  const { box } = brief;
  // Per-park POI tallies (only parks with a code; the area POIs carry a parkCode when NPS attributes them).
  const poiCounts = new Map<string, Record<string, number>>();
  for (const p of brief.pois) {
    if (!p.parkCode) continue;
    const rec = poiCounts.get(p.parkCode) ?? {};
    rec[p.layer] = (rec[p.layer] ?? 0) + 1;
    poiCounts.set(p.parkCode, rec);
  }

  const flag = (on: boolean | undefined, label: string) => (on ? `<span class="badge">${label}</span>` : '');
  const parkSection = (s: AreaPark): string => {
    const counts = poiCounts.get(s.parkCode) ?? {};
    const poiLine = Object.entries(counts)
      .filter(([, n]) => n > 0)
      .map(([k, n]) => `${n} ${esc(LAYER_LABEL[k] ?? k)}`)
      .join(' · ');
    return `<section class="park">
      <h2>${esc(s.name)}${s.designation ? ` <span class="muted">· ${esc(s.designation)}</span>` : ''}</h2>
      <p><span class="k">Coordinates:</span> ${coords(s.lat, s.lng)}</p>
      ${(s.darkSky || s.accessible || s.feeFree) ? `<p>${flag(s.darkSky, 'Dark sky')}${flag(s.accessible, 'Accessible')}${flag(s.feeFree, 'Fee-free')}</p>` : ''}
      ${poiLine ? `<p class="muted">Nearby: ${poiLine}</p>` : ''}
    </section>`;
  };

  const parks = brief.parks.length
    ? brief.parks.map(parkSection).join('\n')
    : '<p class="muted">No parks in this area. Zoom out or pan to a region with National Park sites.</p>';
  const capNote = brief.capped.parks
    ? '<p class="sub">Showing the first 60 parks in view — zoom in for a complete area.</p>'
    : '';

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>National parks in this area — field sheet</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif; color: #1c2b24; margin: 0; padding: 2rem; max-width: 820px; }
  header { border-bottom: 2px solid #2f5e3f; padding-bottom: .75rem; margin-bottom: 1.25rem; }
  h1 { font-size: 1.5rem; margin: 0; color: #2f5e3f; }
  .sub { color: #5a6b62; margin: .25rem 0 0; font-size: .9rem; }
  .park { border: 1px solid #d8e0da; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 1rem; page-break-inside: avoid; }
  h2 { font-size: 1.1rem; margin: 0 0 .5rem; }
  p { margin: .25rem 0; font-size: .9rem; }
  .k { color: #5a6b62; font-weight: 600; }
  .muted { color: #8a978f; }
  .badge { display: inline-block; background: #eef3ef; color: #2f5e3f; border: 1px solid #cdded3; border-radius: 999px; padding: .05rem .5rem; font-size: .75rem; font-weight: 600; margin-right: .35rem; }
  footer { margin-top: 1.5rem; color: #8a978f; font-size: .75rem; border-top: 1px solid #d8e0da; padding-top: .75rem; }
  @media print { body { padding: 0; } .park { border-color: #bbb; } }
</style></head>
<body>
  <header>
    <h1>National parks in this area</h1>
    <p class="sub">${brief.parks.length} park${brief.parks.length === 1 ? '' : 's'} in view · bounds ${coords(box.minLat, box.minLng)} → ${coords(box.maxLat, box.maxLng)}</p>
    ${capNote}
  </header>
  ${parks}
  <footer>Generated by TrailGraph. Verify gate hours, permits, and conditions with NPS.gov and park rangers before you go — TrailGraph is not an official safety source.</footer>
</body></html>`;
}
