import type { TripBrief } from './trip-lab';

/**
 * Printable field-brief HTML (ADR-057) — a self-contained, no-JS, print-optimized one-pager per stop
 * (coordinates, entrance fee, gate/closure notes, visitor centers, campgrounds, drive to next). Pure +
 * unit-tested: the route just fetches `tripBrief` and wraps it. No Chakra (a clean print artifact, and
 * it sidesteps SSR/hydration entirely).
 */
function esc(s: string | null | undefined): string {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string);
}

function coords(lat: number | null, lng: number | null): string {
  return lat != null && lng != null ? `${lat.toFixed(5)}, ${lng.toFixed(5)}` : '—';
}

export function tripBriefHtml(brief: TripBrief): string {
  const dates = brief.startDate ? `${esc(brief.startDate.slice(0, 10))}${brief.endDate ? ` – ${esc(brief.endDate.slice(0, 10))}` : ''}` : '';
  const stops = brief.stops
    .map((s, i) => {
      const num = (s.order ?? i) + 1;
      const alerts = s.alerts.length
        ? `<ul class="alerts">${s.alerts.map((a) => `<li><strong>${esc(a.category)}:</strong> ${esc(a.title)}</li>`).join('')}</ul>`
        : '<p class="muted">No active closures or danger alerts.</p>';
      const vcs = s.visitorCenters.length ? `<p><span class="k">Visitor centers:</span> ${s.visitorCenters.map(esc).join(' · ')}</p>` : '';
      const cgs = s.campgrounds.length ? `<p><span class="k">Campgrounds:</span> ${s.campgrounds.map((c) => esc(c.name)).join(' · ')}</p>` : '';
      const drive = s.driveToNext ? `<p class="drive">↓ ${s.driveToNext.miles} mi · ${s.driveToNext.minutes} min to next stop</p>` : '';
      const dir = s.directionsUrl ? `<p><span class="k">Directions:</span> ${esc(s.directionsUrl)}</p>` : '';
      const fee = s.entranceFee != null ? `$${s.entranceFee} vehicle entrance` : 'fee n/a';
      return `
      <section class="stop">
        <h2><span class="num">${num}</span> ${esc(s.name)}${s.designation ? ` <span class="muted">· ${esc(s.designation)}</span>` : ''}</h2>
        <p><span class="k">Coordinates:</span> ${coords(s.lat, s.lng)} &nbsp; <span class="k">·</span> ${esc(fee)}</p>
        ${dir}${vcs}${cgs}
        <h3>Gate &amp; closure notes</h3>
        ${alerts}
        ${drive}
      </section>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${esc(brief.name)} — field brief</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif; color: #1c2b24; margin: 0; padding: 2rem; max-width: 820px; }
  header { border-bottom: 2px solid #2f5e3f; padding-bottom: .75rem; margin-bottom: 1.25rem; }
  h1 { font-size: 1.5rem; margin: 0; color: #2f5e3f; }
  .sub { color: #5a6b62; margin: .25rem 0 0; font-size: .9rem; }
  .stop { border: 1px solid #d8e0da; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 1rem; page-break-inside: avoid; }
  h2 { font-size: 1.1rem; margin: 0 0 .5rem; }
  h3 { font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; color: #5a6b62; margin: .75rem 0 .25rem; }
  .num { display: inline-block; min-width: 1.4rem; height: 1.4rem; line-height: 1.4rem; text-align: center; background: #2f5e3f; color: #fff; border-radius: 999px; font-size: .8rem; margin-right: .4rem; }
  p { margin: .25rem 0; font-size: .9rem; }
  .k { color: #5a6b62; font-weight: 600; }
  .muted { color: #8a978f; }
  .alerts { margin: .25rem 0; padding-left: 1.1rem; }
  .alerts li { font-size: .9rem; margin: .15rem 0; }
  .drive { color: #b5651d; font-weight: 600; margin-top: .6rem; }
  footer { margin-top: 1.5rem; color: #8a978f; font-size: .75rem; border-top: 1px solid #d8e0da; padding-top: .75rem; }
  @media print { body { padding: 0; } .stop { border-color: #bbb; } }
</style></head>
<body>
  <header>
    <h1>${esc(brief.name)}</h1>
    <p class="sub">Field brief${dates ? ` · ${dates}` : ''} · ${brief.stops.length} stop${brief.stops.length === 1 ? '' : 's'}</p>
  </header>
  ${stops}
  <footer>Generated by TrailGraph. Verify gate hours, permits, and conditions with NPS.gov and park rangers before you go — TrailGraph is not an official safety source.</footer>
</body></html>`;
}
