import { describe, it, expect } from 'vitest';
import { NPS_VISITATION, VISITATION_YEARS } from './visitation-data';

/**
 * Coverage + shape guard for the bundled NPS monthly-visitation dataset (generated by
 * scripts/build-visitation-dataset.ts). Flags a regression if a future regen drops coverage or shape.
 */
describe('NPS_VISITATION (bundled dataset)', () => {
  it('covers a large share of parks (the whole point — chart on every park)', () => {
    expect(NPS_VISITATION.length).toBeGreaterThan(350);
  });

  it('every record has a 4-letter parkCode and exactly 12 months of non-negative integers', () => {
    for (const r of NPS_VISITATION) {
      expect(r.parkCode).toMatch(/^[a-z]{4}$/);
      expect(r.monthly).toHaveLength(12);
      expect(r.monthly.every((v) => Number.isInteger(v) && v >= 0)).toBe(true);
      expect(r.monthly.some((v) => v > 0)).toBe(true); // no all-zero records
    }
  });

  it('has no duplicate parkCodes', () => {
    const codes = NPS_VISITATION.map((r) => r.parkCode);
    expect(new Set(codes).size).toBe(codes.length);
  });

  it('includes flagship parks with sensible seasonal shapes (summer-peak)', () => {
    const byCode = new Map(NPS_VISITATION.map((r) => [r.parkCode, r.monthly]));
    for (const code of ['yell', 'glac', 'grca', 'zion', 'acad']) {
      expect(byCode.has(code), `${code} missing`).toBe(true);
    }
    // Yellowstone & Glacier peak in summer, not winter.
    const yell = byCode.get('yell')!;
    const jul = yell[6];
    const jan = yell[0];
    expect(jul).toBeGreaterThan(jan * 3);
  });

  it('exposes the averaged year range for honest labeling', () => {
    expect(VISITATION_YEARS).toHaveLength(2);
    expect(VISITATION_YEARS[0]).toBeLessThanOrEqual(VISITATION_YEARS[1]);
  });
});
